language: java

jdk: openjdk8

cache:
  directories:
  - $HOME/.m2

before_cache:
  - rm -rf $HOME/.m2/repository/org/openmrs

before_install:
  - CHROME_URL="https://github.com/webnicer/chrome-downloads/blob/master/x64.deb/google-chrome-stable_89.0.4389.72-1_amd64.deb?raw=true"
  - CHROME_DRIVER_URL="https://chromedriver.storage.googleapis.com/89.0.4389.23/chromedriver_linux64.zip"
  - curl ${CHROME_URL} -O
  - sudo dpkg -i google-chrome-*.deb*
  - rm google-chrome-stable_89.0.4389.72-1_amd64.deb

script:
    - git clone https://github.com/openmrs/openmrs-contrib-uitestframework.git
    - cd openmrs-contrib-uitestframework
    - git fetch --all
    - git checkout qa
    - curl ${CHROME_DRIVER_URL} -O
    - rm src/main/resources/chromedriver/linux/chromedriver
    - unzip chromedriver_linux64.zip -d src/main/resources/chromedriver/linux
    - mvn clean install
    - cd ../
    - git clone https://github.com/openmrs/openmrs-distro-referenceapplication.git
    - cd openmrs-distro-referenceapplication/ui-tests
    - git fetch --all
    - git checkout qa
    - mvn clean install
    - cd ../../
    - rm -rf openmrs-contrib-uitestframework
    - rm -rf openmrs-distro-referenceapplication
    - mvn clean install
