language: java

jdk: openjdk8

cache:
  directories:
  - $HOME/.m2

install: true
  
before_cache:
  - rm -rf $HOME/.m2/repository/org/openmrs
  
script:
    git clone https://github.com/openmrs/openmrs-contrib-uitestframework.git;
    cd openmrs-contrib-uitestframework;
    git fetch --all;
    git checkout qa;
    mvn clean install;
    cd ../;
    git clone https://github.com/openmrs/openmrs-distro-referenceapplication.git;
    cd openmrs-distro-referenceapplication/ui-tests;
    git fetch --all;
    git checkout qa;
    mvn clean install;
    cd ../../;
    rm -rf openmrs-contrib-uitestframework;
    rm -rf openmrs-distro-referenceapplication;
    mvn clean install;
